### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by vicheanath** [heabeounMKTO/auto_label#1]
@heabeounMKTO please write down todo 
- [ ] GUI @vicheanath 
- [ ] Some Task
- [ ] hehe

**Comment by vicheanath** [comment]
I don't know any think from me I think this project should be have GUI  ex: tkinter (python)

**Comment by heabeounMKTO** [comment]
> I don't know any think from me I think this project should be have GUI ex: tkinter (python)

i will fill in the todo soon , i have plans for web dashboard to show stats etc , similar to roboflow's dataset health page
